### PR TITLE
solves bug of projection bounds

### LINKED ISSUE #23: changing topojson or fit should update projection
### Expected Behavior
When changing the following methods, the projection bounds should be re-calculated:
- `fitObject`
- `fitFilter`
- `fitKey`
- `topojson`
- `topojsonFilter`
- `topojsonKey`

### Current Behavior
Currently, the first projection bound calculated is maintained.

### Steps to Reproduce (for bugs)
http://jsfiddle.net/14L2qn89/4/

### PR DESCRIPTION
**Pull request by cnavarreteliz**
(closes #23)

### Description

This bug was caused because we override `this._zoomSet = true`. That property didn't update of the bounds when you re-render the geomap. For to solve it, I deleted that code line.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

### CODE REVIEW

**Review by davelandry — CHANGES_REQUESTED** [review]
The purpose of `zoomSet` is so that the projection math to determine the zoom is not calculated on every render (for example, as the user changes the timeline).

Just deleting this line is not good form, as the variable is now set to false but never used. We should set `this._zoomSet = false;` within the methods listed in the issue so that it gets calculated if those methods change.

**Comment by cnavarreteliz** [comment]
I defined an `if` statement that checks changes in every render.

File: src/Geomap.js [hunk 1]
```diff
@@ -241,6 +241,8 @@ export default class Geomap extends Viz {
     const r = scales[`scale${this._pointSizeScale.charAt(0).toUpperCase()}${this._pointSizeScale.slice(1)}`]()
       .domain(extent(pointData, (d, i) => this._pointSize(d, i)))
       .range([this._pointSizeMin, this._pointSizeMax]);
+    
+    if (this._fitObject || this._fitFilter || this._fitKey || this._topojson || this._topojsonFilter || this._topojsonKey) this._zoomSet = false;
```
Comment (davelandry) [inline src/Geomap.js]: This logic will always reset the zoomSet if any of those methods are set... which is not the desired behavior. We want to reset the zoomSet if the user has CHANGED one of these methods. You need to add this reset directly into each one of these methods where the value gets assigned. For example:

```js
topojson(_, f) {
     if (arguments.length) {
       const prev = this._queue.find(q => q[3] === "topojson");
       const d = [load.bind(this), _, f, "topojson"];
       if (prev) this._queue[this._queue.indexOf(prev)] = d;
       else this._queue.push(d);
       this._zoomSet = false;
       return this;
     }
     return this._topojson;
   }
```

**Review by davelandry — CHANGES_REQUESTED** [review]

File: src/Geomap.js (hunk 1 above)
Comment (cnavarreteliz) [reply src/Geomap.js]: Thanks for your feedback, teaching and orienting me about d3plus. I've seen improves in my ability of to solve bugs related with the library :)
